# traefik-endpoints-access.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-endpoints-access
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: kube-system
roleRef:
  kind: Role
  name: endpoint-reader
  apiGroup: rbac.authorization.k8s.io
