apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: pompetrack-core
  labels:
    app: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      serviceAccountName: ingestion
      imagePullSecrets:
        - name: gitlab-regcred
      containers:
        - name: ingestion
          image: registry.phylcero.fr/garth/pompetrack/ingestion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            # Secrets via fichiers (compatibles avec ton entrypoint)
            - name: MINIO_ACCESS_KEY_ID_FILE
              value: /var/run/secrets/minio/apiAccessKey
            - name: MINIO_SECRET_ACCESS_KEY_FILE
              value: /var/run/secrets/minio/apiSecretKey

            # config MinIO
            - name: MINIO_ENDPOINT
              value: "http://pompetrack-core-minio:9000"

            - name: CLIENT_ID_FILE
              value: /var/run/secrets/MEDPLUM_CLIENT_ID
            - name: CLIENT_SECRET_FILE
              value: /var/run/secrets/MEDPLUM_CLIENT_SECRET


          volumeMounts:
            - name: minio-creds
              mountPath: /var/run/secrets/minio
              readOnly: true
            - name: medplum-creds-ingestion
              mountPath: /var/run/secrets
              readOnly: true
            - name: medplum-client-ids
              mountPath: /var/run/secrets
              readOnly: true

      volumes:
        - name: minio-creds
          secret:
            secretName: minio-app-creds
            items:
              - key: apiAccessKey
                path: apiAccessKey
              - key: apiSecretKey
                path: apiSecretKey
        - name: medplum-creds-ingestion
          secret:
            secretName: ingestion-medplum-client
            defaultMode: 0400
            items:
              - key: MEDPLUM_CLIENT_ID
                path: MEDPLUM_CLIENT_ID
              - key: MEDPLUM_CLIENT_SECRET
                path: MEDPLUM_CLIENT_SECRET  
        - name: medplum-client-ids
          secret:
            secretName: medplum-clients
            defaultMode: 0400
            items:
              - key: TOKEN_AUDIENCE_WORKER_FHIR
                path: TOKEN_AUDIENCE_WORKER_FHIR
              - key: TOKEN_AUDIENCE_STREAMLIT
                path: TOKEN_AUDIENCE_STREAMLIT       
              - key: TOKEN_AUDIENCE_WORKER_SQLITE
                path: TOKEN_AUDIENCE_WORKER_SQLITE