apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: pompetrack-core
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      serviceAccountName: streamlit
      imagePullSecrets:
        - name: gitlab-regcred
      containers:
        - name: streamlit
          image: registry.phylcero.fr/garth/pompetrack/streamlit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
              name: http

          env:
            # config JWT
            - name: MEDPLUM_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: medplum-streamlit-creds
                  key: MEDPLUM_CLIENT_ID
            - name: MEDPLUM_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: medplum-streamlit-creds
                  key: MEDPLUM_CLIENT_SECRET

          envFrom:
            - configMapRef:
                name: medplum-ids
    

