apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1

    metrics:
      prometheus:
        enabled: true
        entryPoint: metrics

    ports:
      web:
        hostPort: null
      websecure:
        hostPort: null
      metrics:
        port: 8082
        expose:
          default: true
        exposedPort: 8082
        protocol: TCP

    additionalArguments:
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"