apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    metrics:
      prometheus:
        enabled: true
        entryPoint: metrics
    ports:
      metrics:
        port: 9100
        expose:
          default: true
        exposedPort: 9100
        protocol: TCP
    additionalArguments:
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"