apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr-postgresql-istio-mutual
  namespace: airflow
spec:
  host: airflow-postgresql.airflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
