location / {

  if ($request_method = OPTIONS) {
      add_header Access-Control-Allow-Origin https://provider.phylcero.fr;
      add_header Access-Control-Allow-Credentials true;
      add_header Access-Control-Allow-Headers Authorization,Content-Type,X-Medplum;
      add_header Access-Control-Allow-Methods GET,POST,PUT,PATCH,DELETE,OPTIONS;
      return 204;
  }

  proxy_pass http://192.168.2.88:32110;

  proxy_hide_header Access-Control-Allow-Origin;
  proxy_hide_header Access-Control-Allow-Credentials;

  add_header Access-Control-Allow-Origin https://provider.phylcero.fr always;
  add_header Access-Control-Allow-Credentials true always;

  proxy_redirect off;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
