apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplum
  namespace: medplum
spec:
  template:
    spec:
      containers:
        - name: medplum
          livenessProbe:
            timeoutSeconds: 5
          readinessProbe:
            timeoutSeconds: 5
          startupProbe:
            timeoutSeconds: 5
