airflow:
  enabled: true
  executor: KubernetesExecutor
  
  dags:
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: local-path
      accessMode: ReadWriteOnce


  airflow:
    config:
      core:
        executor: KubernetesExecutor
        load_examples: "false"

      api:
        base_url: "http://airflow.lan"

      webserver:
        enable_proxy_fix: "True"

  postgresql:
    enabled: true

    auth:
      existingSecret: airflow-postgresql-auth
      username: airflow
      database: airflow

    primary:
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 800m
          memory: 1Gi

  redis:
    enabled: false

  flower:
    enabled: false

  webserver:
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

  scheduler:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

  triggerer:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  ingress:
    enabled: false

  fernetKeySecretName: airflow-fernet-key
  webserverSecretKeySecretName: airflow-webserver-secret-key
  apiSecretKeySecretName: airflow-api-secret-key

  data:
    metadataSecretName: airflow-metadata
