airflow:
  enabled: true
  executor: KubernetesExecutor
  
  extraPipPackages:
    - apache-airflow-providers-amazon

  extraEnvVarsSecret: airflow-medplum-client

  config:
    core:
      executor: KubernetesExecutor

    api:
      base_url: "http://airflow.lan"

    webserver:
      enable_proxy_fix: "True"

  dags:
    persistence:
      enabled: true
      existingClaim: airflow-dags-pvc

  postgresql:
    enabled: true
    auth:
      existingSecret: airflow-postgresql-auth
      username: airflow
      database: airflow
    primary:
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 800m
          memory: 1Gi

  redis:
    enabled: false

  flower:
    enabled: false

  webserver:
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podAnnotations:
      traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.43.0.1/32"
    env:
      - name: PYTHONPATH
        value: /opt/airflow/dags
      - name: AIRFLOW_CONN_MINIO_LOGS
        valueFrom:
          secretKeyRef:
            name: airflow-minio-conn
            key: AIRFLOW_CONN_MINIO_LOGS

  scheduler:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podAnnotations:
      traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.43.0.1/32"
    env:
      - name: PYTHONPATH
        value: /opt/airflow/dags
      - name: AIRFLOW_CONN_MINIO_LOGS
        valueFrom:
          secretKeyRef:
            name: airflow-minio-conn
            key: AIRFLOW_CONN_MINIO_LOGS

  dagProcessor:
    enabled: true
    podAnnotations:
      traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.43.0.1/32"
    env:
      - name: PYTHONPATH
        value: /opt/airflow/dags
      - name: AIRFLOW_CONN_MINIO_LOGS
        valueFrom:
          secretKeyRef:
            name: airflow-minio-conn
            key: AIRFLOW_CONN_MINIO_LOGS

  triggerer:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    podAnnotations:
      traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.43.0.1/32"
    envFrom:
      - name: AIRFLOW_CONN_MINIO_LOGS
        valueFrom:
          secretKeyRef:
            name: airflow-minio-conn
            key: AIRFLOW_CONN_MINIO_LOGS

  ingress:
    enabled: false

  fernetKeySecretName: airflow-fernet-key
  webserverSecretKeySecretName: airflow-webserver-secret-key
  apiSecretKeySecretName: airflow-api-secret-key

  data:
    metadataSecretName: airflow-metadata

  env: 
    - name: AIRFLOW__LOGGING__REMOTE_LOGGING
      value: "True"
    - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
      value: "s3://airflow-logs"
    - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
      value: "minio_logs"
    - name: AIRFLOW__SECRETS__BACKENDS
      value: airflow.secrets.environment_variables.EnvironmentVariablesBackend

 