kube-prometheus-stack:

  fullnameOverride: prometheus

  ## ---------------------------
  ## GLOBAL
  ## ---------------------------
  global:
    rbac:
      create: true

  ## ---------------------------
  ## PROMETHEUS
  ## ---------------------------
  prometheus:
    prometheusSpec:
      replicas: 1

      retention: 10d

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 2Gi
          cpu: 1000m

      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}

      additionalScrapeConfigs:
        - job_name: 'proxmox'
          static_configs:
            - targets: ['192.168.2.5:9221']
          metrics_path: /metrics
          params:
            module: [default]
            target: ['192.168.2.5']

        - job_name: 'traefik'
          static_configs:
            - targets:
              # Traefik dans kube-system, port métriques 8082
              - 'traefik.kube-system.svc.cluster.local:8082'

      podMetadata:
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9100"

  ## ---------------------------
  ## ALERTMANAGER
  ## ---------------------------
  alertmanager:
    alertmanagerSpec:
      replicas: 1

      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi

  ## ---------------------------
  ## GRAFANA
  ## ---------------------------
  grafana:
    enabled: true

    adminUser: admin
    adminPassword: admin

    persistence:
      enabled: true
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    service:
      type: NodePort
      nodePort: 30007

  ## ---------------------------
  ## NODE EXPORTER
  ## ---------------------------
  nodeExporter:
    enabled: true
    hostNetwork: false

  ## ---------------------------
  ## KUBE STATE METRICS
  ## ---------------------------
  kubeStateMetrics:
    enabled: true

  ## ---------------------------
  ## COMPONENTS K3s CLEANUP
  ## ---------------------------
  kubeControllerManager:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  kubeEtcd:
    enabled: false
