apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-ollama-vm
  namespace: llm-agent
spec:
  podSelector:
    matchLabels:
      allow-external-ollama: "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.2.189/32
      ports:
        - protocol: TCP
          port: 11434