apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui-lan
  namespace: llm-agent
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`open-webui.lan`) || Host(`open-webui.192.168.2.88.nip.io)
      kind: Rule
      middlewares:
        - name: lan-only
          namespace: llm-agent 
      services:
        - name: open-webui
          port: 8080