apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medplum-api
spec:
  ingressClassName: traefik
  rules:
    - host: api.phylcero.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pompetrack-medplum-service
                port:
                  number: 80
