minio:
  mode: standalone

  existingSecret: minio-root

  replicas: 1

  persistence:
    enabled: true
    size: 20Gi
    storageClass: nfs-client

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi

  service:
    type: ClusterIP

  consoleService:
    type: ClusterIP

postgresql:
  fullnameOverride: pompetrack-core-postgresql
  image: registry.phylcero.fr/garth/pompetrack/pgsql-pompetrack-core:latest
  auth:
      existingSecret: postgresql-auth
      username: pompetrack-user
      database: pompetrack
  primary:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 800m
        memory: 1Gi
    persistence:
      enabled: true
      size: 4Gi
      storageClass: local-path

prometheus-postgres-exporter:
  enabled: true
  fullnameOverride: "pompetrack-core-postgres-exporter"
  config:
    datasource:
      host: "pompetrack-core-postgresql.pompetrack-core.svc.cluster.local"
      user: "pompetrack-user"
      passwordSecret:
        name: postgresql-auth
        key: password
      port: "5432"
      database: "pompetrack"
      sslmode: disable