apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape-medplum
  namespace: medplum
spec:
  podSelector: {}   # Tous les pods du namespace medplum
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9187   # postgres-exporter
        - protocol: TCP
          port: 9121   # redis-exporter