apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pg-pompetrack-core-metrics-from-prometheus
  namespace: pompetrack-core
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-postgres-exporter
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - protocol: TCP
      port: 9187

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pg-pompetrack-core-metrics-to-prometheus
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: pompetrack-core
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus-postgres-exporter
    ports:
    - protocol: TCP
      port: 9187
