apiVersion: v1
kind: Service
metadata:
  name: medplum-mesh
  namespace: medplum
spec:
  selector:
    app.kubernetes.io/instance: medplum
    app.kubernetes.io/name: medplum
  ports:
    - name: http
      port: 8103
      targetPort: 8103
