apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
  namespace: medplum
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: medplum
spec:
  headers:
    accessControlAllowOriginList:
      - http://provider.lan
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - Authorization
      - Content-Type
      - X-Medplum
    accessControlAllowCredentials: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: medplum-app
  namespace: medplum
spec:
  entryPoints:
    - web
  routes:

    # API via /api
    - match: Host(`medplum.phylcero.fr`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: cors
        - name: strip-api-prefix
      services:
        - name: medplum-service
          port: 80

    # Auth endpoints
    - match: Host(`medplum.phylcero.fr`) && PathPrefix(`/auth`)
      kind: Rule
      middlewares:
        - name: cors
      services:
        - name: medplum-service
          port: 80

    # OAuth endpoints
    - match: Host(`medplum.phylcero.fr`) && PathPrefix(`/oauth2`)
      kind: Rule
      middlewares:
        - name: cors
      services:
        - name: medplum-service
          port: 80

    # Well-known endpoints
    - match: Host(`medplum.phylcero.fr`) && PathPrefix(`/.well-known`)
      kind: Rule
      middlewares:
        - name: cors
      services:
        - name: medplum-service
          port: 80

    # FHIR endpoints
    - match: Host(`medplum.phylcero.fr`) && PathPrefix(`/fhir`)
      kind: Rule
      middlewares:
        - name: cors
      services:
        - name: medplum-service
          port: 80

    # UI
    - match: Host(`medplum.phylcero.fr`)
      kind: Rule
      services:
        - name: medplum-app
          port: 3000
