apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medplum-provider
  namespace: medplum
spec:
  ingressClassName: traefik
  rules:
  - host: provider.phylcero.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: medplum-provider
            port:
              number: 80
